# Generated by Django 5.2.5 on 2025-08-11 19:59

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_comment_tags_post_tags"),
    ]

    operations = [TrigramExtension()]
